apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oracle
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: oracle
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.ports.database }}
        - containerPort: {{ .Values.service.ports.apex }}
        env:
        - name: ORACLE_PWD
          value: "{{ .Values.env.oraclePwd }}"
        volumeMounts:
        - mountPath: {{ .Values.persistence.mountPath }}
          name: oracle-storage
      volumes:
      - name: oracle-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc